"""Update database schema

Revision ID: 27c7ad25a1d9
Revises: 
Create Date: 2023-07-16 17:48:30.390837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c7ad25a1d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.alter_column('score',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
